### ISSUE TITLE
Add FAQ skill

### ISSUE THREAD

**Issue by Xyaneon** [Xyaneon/LTUAssistantPlus#16]
An important project goal is to be able to talk to the assistant and ask it questions it can find the answers to from the LTU website, such as questions about a department. This will likely involve scraping the site to build up a local database of some sort for searching, the processing the user's request so that it knows what to search for.

## Sample questions* ##
- "Who is the department chair of the Mathematics and Computer Science department?"
- "Where is Dr. Chung's office?"
- "What concentrations are available for a Bachelor's of Science in Computer Science?"

*\* The exact questions may change.*

## Prerequisites ##
- [x] Add skill structure (#30)
- ~~Add web crawling (#23)~~
- [x] Add web scraping (#25)
- [x] Add local database for website text (#24)
- [x] Add translation of user questions into database queries (#28)

**Comment by Xyaneon** [comment]
The skill is added, but not fully integrated at this time. Switch to the [`getAnserFromDB`][branch] branch to check this out and run it from the separate files.

[branch]: https://github.com/Xyaneon/LTUAssistantPlus/tree/getAnserFromDB
